### ISSUE TITLE
Code samples for basic setup

### ISSUE THREAD

**Issue by TBSliver** [fkhadra/react-toastify-doc#14]
Add basic example code on the [installation](https://fkhadra.github.io/react-toastify/installation) page instead of having to watch a 10 minute video. Also means that less mistakes will be made, even when using said video, so that you can copy and paste the basics easily.

**Comment by TBSliver** [comment]
Nevermind, found the actual demo code on the next page - Instead I would recommend moving the code from https://fkhadra.github.io/react-toastify/the-gist-of-react-toastify to be on the same page as installation...

**Comment by fkhadra** [comment]
Hey @TBSliver,

Thanks for your comment I'll take it into account and do the change whenever I can.

**Comment by utkarshgupta137** [comment]
I second this. It took me an hour to figure out why there was a big cross taking the full screen. I forgot to import the css -.-
