### ISSUE TITLE
Update default code theme to display copy badge 

### ISSUE THREAD

**Issue by heytulsiprasad** [fkhadra/react-toastify-doc#3]
The default code theme of the code snippets (in light theme) doesn't show the *Copy* badge on the top right corner, but shows a black box with no badge text in it. However, it shows up in dark theme as fine.

## Reproduce the issue

I've tried opening the site on these browsers, of which I've attached a screenshot of a random codeblock.
- **Microsoft Edge**
![Annotation 2020-07-21 142854](https://user-images.githubusercontent.com/52394293/88034827-db031c80-cb5e-11ea-8bb4-c88ab52b6fa1.png)

- **Mozilla Firefox**
![Annotation 2020-07-21 142702](https://user-images.githubusercontent.com/52394293/88034870-e9e9cf00-cb5e-11ea-81bc-5cbedc1e6936.png)

I believe this issue would be the same for all browsers (as it might be rendering the same theme everywhere)

## Possible fixes

I think it can be solved if we add a different code theme for light mode than using same for both dark and light modes.

**Comment by heytulsiprasad** [comment]
## Update

I cloned the repo and added the *github* light theme for code blocks (in light mode) and now the **copy** badge shows up in light mode, as well as in dark mode.

This is a screenshot of how it looks.

![https://i.imgur.com/5FKoKjV.png](https://i.imgur.com/5FKoKjV.png)

Also if you'd like, I would love to make a PR from my local branch. I hope you like it.

**Comment by fkhadra** [comment]
Hey @heytulsiprasad,

Really appreciate, could you open a PR ? Thanks

**Comment by heytulsiprasad** [comment]
Sure. Thanks for allowing me! :tada:
