### ISSUE TITLE
Include 'toastId' prop in toast API docs page

### ISSUE THREAD

**Issue by vgeorge** [fkhadra/react-toastify-doc#30]
The PR https://github.com/fkhadra/react-toastify/pull/220 enabled setting the toast id manually by passing a `toastId` prop, but this doesn't seem to be reflected in [toast() API docs](https://fkhadra.github.io/react-toastify/api/toast). Happy to create a PR with a fix if needed.

**Comment by fkhadra** [comment]
Thanks for reporting the issue
