### ISSUE TITLE
Contribute link is broken

### ISSUE THREAD

**Issue by Tamashii90** [fkhadra/react-toastify-doc#39]
https://fkhadra.github.io/react-toastify/introduction/CONTRIBUTING.md

The contribute link on the introduction page is copy-pasted from the main repo's [README](https://github.com/fkhadra/react-toastify/blob/master/README.md), and because there's no CONTRIBUTING.md file under the docs directory, Docusaurus returns 404.

I would like to work on this.

**Comment by fkhadra** [comment]
Thanks for reporting the issue. (sorry for the late answer) I fixed it
